### PR TITLE
Fix cancellation ID existentials in iOS 14

### LINKED ISSUE #2233: DismissEffect does not work on iOS14
### Description

DismissEffect does not work on iOS14.

Nothing happens when I run the code below on iOS14.

```swift
struct CoreReducer: ReducerProtocol {
    @Dependency(\.dismiss) private var dismiss

    func reduce(into state: inout State, action: Action) -> EffectTask<Action> {
        switch action {
        ...
            return .fireAndForget {
                // Nothing happens.
                await dismiss()
            }
        }
    }
}
```

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

Screen closes after executing DismissEffect.

### Actual behavior

Screen does not close after executing DismissEffect.

### Steps to reproduce

1. Transition to any screen on iOS14
2. Execute DismissEffect on the transition destination screen

### The Composable Architecture version information

0.54.1

### Destination operating system

iOS 14.5

### Xcode version information

14.3

### Swift Compiler version information

```shell
swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
```

### PR DESCRIPTION
**Pull request by stephencelis**
Fixes #2233.

On iOS 14, `DismissEffect` is broken because effect cancellation uses `AnyHashable` throughout, which can lead to nested `AnyHashable(AnyHashable(...))` IDs, which can hash differently depending on the level of nesting. By preserving the hashable ID up to being stored in the internal cancellation token type, we can avoid a hash lookup failure that prevents a dismissal from happening.

### CODE REVIEW

File: Sources/ComposableArchitecture/Effects/Cancellation.swift [hunk 1]
```diff
@@ -182,7 +182,7 @@ extension Task where Success == Never, Failure == Never {
   /// Cancel any currently in-flight operation with the given identifier.
   ///
   /// - Parameter id: An identifier.
-  public static func cancel<ID: Hashable & Sendable>(id: ID) {
+  public static func cancel<ID: Hashable>(id: ID) {
```
Comment (stephencelis) [inline Sources/ComposableArchitecture/Effects/Cancellation.swift:185]: This change is mainly to be consistent. I also tried to mark _everything_ `Hashable & Sendable` but it bled out and introduced warnings to existing code, so I held off on that for now (we could explore it again in another PR).

File: Sources/ComposableArchitecture/Reducer/Reducers/PresentationReducer.swift [hunk 2]
```diff
@@ -477,8 +477,8 @@ extension Task where Success == Never, Failure == Never {
   }
 }
 extension EffectPublisher {
-  internal func _cancellable(
-    id: AnyHashable = _PresentedID(),
+  internal func _cancellable<ID: Hashable>(
+    id: ID = _PresentedID(),
```
Comment (stephencelis) [inline Sources/ComposableArchitecture/Reducer/Reducers/PresentationReducer.swift:481]: I think this is safe for the versions of Swift we support, but we could also create overloads...

**Comment by sadiklar** [comment]
13 Tem 2023 Per 19:19 tarihinde Stephen Celis ***@***.***>
şunu yazdı:

**Review by mbrandonw — APPROVED** [review]
