### PR TITLE
Fix view state binding equatability

### LINKED ISSUE #2253: View  with the new @BindingViewState and BindingViewStore not updated after an .onAppear/.task
### Description

When a feature's state should be updated from UserDefaults or a database a .onAppear or .task modifier could be used to perform the action.
With the new @BindingViewState and BindingViewStore the feature's state is updated, the control using the Binding also but not e.g. a TextView displaying the state. In the sample code below one can force an update if another (useless in this example)ViewState property without the @BindingViewState property wrapper is changed (remove the comments on the corresponding lines).

In addition Xcode crashes if the preview is activated.

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

The Text view showing the state's property should also be updated.
Xcode should not crash showing the preview. 

### Actual behavior

The Text view is not updated and Xcode crashes showing the preview.

### Steps to reproduce

```
import ComposableArchitecture
import SwiftUI

struct Counter: ReducerProtocol {
  struct State: Equatable {
    @BindingState var count: Double = 0.0
  }

  enum Action: BindableAction, Equatable {
    case binding(BindingAction<State>)
    case refreshCounter
  }

  public var body: some ReducerProtocol<State, Action> {
    BindingReducer()
    Reduce { state, action in
      switch action {
        case .binding:
          return .none
        case .refreshCounter:
          // could come from UserDefaults or a database
          state.count = 13
          return .none
      }
    }
  }
}

struct CounterView: View {
  let store: StoreOf<Counter>

  struct ViewState: Equatable {
    @BindingViewState var count: Double
//    let countValue: Double

    init(store: BindingViewStore<Counter.State>) {
      self._count = store.$count
//      self.countValue = store.count
    }
  }

  var body: some View {
    WithViewStore(self.store, observe: ViewState.init) { viewStore in
      VStack {
        Text("Slider value: \(Int(viewStore.count))")

        Slider(value: viewStore.$count, in: 0...20, step: 1)
          .tint(.accentColor)
      }
      .task {
        viewStore.send(.refreshCounter)
      }
    }
  }
}

struct CounterView_Previews: PreviewProvider {
  static var previews: some View {
    CounterView(
      store: Store(initialState: Counter.State(count: 11)) {
        Counter()
      }
    )
  }
}
```

### The Composable Architecture version information

0.55.0

### Destination operating system

iOS 16.4

### Xcode version information

14.3.1

### Swift Compiler version information

```shell
Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
```

### PR DESCRIPTION
**Pull request by stephencelis**
Fixes #2253.

If a store state change results in only updating a view store's `BindingViewState`, it was considered equivalent, since the `Binding` would always contain the latest value. This PR fixes things by holding a snapshot of state in `BindingViewState` instead.

### CODE REVIEW

File: Examples/CaseStudies/SwiftUICaseStudies/03-NavigationStack.swift [hunk 1]
```diff
@@ -121,19 +121,19 @@ struct NavigationDemoView: View {
       switch $0 {
       case .screenA:
         CaseLet(
-          state: /NavigationDemo.Path.State.screenA,
+          /NavigationDemo.Path.State.screenA,
```
Comment (stephencelis) [inline Examples/CaseStudies/SwiftUICaseStudies/03-NavigationStack.swift:124]: Unrelated warnings I noticed.

File: Sources/ComposableArchitecture/SwiftUI/Binding.swift [hunk 2]
```diff
@@ -121,6 +121,139 @@ extension BindingState: CustomDebugStringConvertible where Value: CustomDebugStr
 
 extension BindingState: Sendable where Value: Sendable {}
 
+/// An action that describes simple mutations to some root state at a writable key path.
+///
+/// Used in conjunction with ``BindingState`` and ``BindableAction`` to safely eliminate the
+/// boilerplate typically associated with mutating multiple fields in state.
+///
+/// Read <doc:Bindings> for more information.
+public struct BindingAction<Root>: Equatable, @unchecked Sendable {
```
Comment (stephencelis) [inline Sources/ComposableArchitecture/SwiftUI/Binding.swift:130]: Reorganized the file so that all the view stuff is at the bottom...makes reading the diff a lil more difficult but will point out the actual change.

File: Sources/ComposableArchitecture/SwiftUI/Binding.swift [hunk 3]
```diff
@@ -151,13 +284,87 @@ extension BindableAction {
...
+}
+
 /// A property wrapper type that can designate properties of view state that can be directly
 /// bindable in SwiftUI views.
 ///
 /// Read <doc:Bindings> for more information.
 @propertyWrapper
 public struct BindingViewState<Value> {
   let binding: Binding<Value>
+  let initialValue: Value
```
[the remark this answers is not in the document]
Comment (stephencelis) [reply Sources/ComposableArchitecture/SwiftUI/Binding.swift:362]: (Writing assertions against view state is rare, so `TestStore` tests against the plain `BindingState` will work just fine, but the above behavior could be a gotcha if folks try to unit test view state that contain `@BindingViewState`.)

**Comment by lukeredpath** [comment]
Could this also be a fix to an issue I've observed with `TestStore` tests that assert receiving a binding action?

image

**Comment by robfeldmann** [comment]
I came tonight to see if this bug had been reported yet and was happy to know it was and that this PR is in the works. 👏 

FWIW, I took the [salient change](https://github.com/pointfreeco/swift-composable-architecture/pull/2255#discussion_r1251103564) and ported it to `prerelease/1.0` and it worked perfectly. 🎉

**Comment by stephencelis** [comment]
> Could this also be a fix to an issue I've observed with `TestStore` tests that assert receiving a binding action?

I don't _think_ this PR would address such a problem, but would be happy to check if you have a simple repro. Got anything you can share, like a failing test case?

**Comment by lukeredpath** [comment]
@stephencelis here's a gist that demonstrates the problem:
https://gist.github.com/lukeredpath/96ac8bfea295f0b729408ecce694ca26
Screenshot 2023-07-06 at 17 39 25

**Comment by peramaic** [comment]
@stephencelis the code in branch fix-binding-view-state fixes the problem with updating the view, but opening the preview (see my example in #2253) still crashes Xcode.
Any ideas?

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Xcode [71408]
Path:                  /Applications/Xcode.app/Contents/MacOS/Xcode
Identifier:            com.apple.dt.Xcode
Version:               14.3.1 (21815)
Build Info:            IDEFrameworks-21815000000000000~2 (14E300c)
App Item ID:           497799835
App External ID:       857328487
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-07-07 07:52:47.0811 +0200
OS Version:            macOS 13.4.1 (22F82)
Report Version:        12
Anonymous UUID:        AD420AAB-7ACD-9973-38CC-839B97E0CC8E

Sleep/Wake UUID:       F8550F6F-5B3F-4A64-899B-6D26C3592396

Time Awake Since Boot: 360000 seconds
Time Since Wake:       1017 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
abort() called


Application Specific Signatures:
DVTInvalidation.swift:37@@DVTAssertInvalidatableObjectIsValid(_:)

Thread 0 Crashed:
0   libsystem_kernel.dylib        	       0x1983cc724 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x198403c28 pthread_kill + 288
2   libsystem_c.dylib             	       0x198311ae8 abort + 180
3   IDEKit                        	       0x10980f220 +[IDEAssertionHandler _handleAssertionWithLogString:assertionSignature:assertionReason:extraBacktrace:] + 980
4   IDEKit                        	       0x10980fb00 -[IDEAssertionHandler handleFailureInFunction:fileName:lineNumber:assertionSignature:messageFormat:arguments:] + 772
5   DVTFoundation                 	       0x1061b1c70 _DVTAssertionHandler + 472
6   DVTFoundation                 	       0x1061b20dc _DVTAssertFromSwift + 260
7   DVTFoundation                 	       0x10626f4bc specialized withVaList<A>(_:_:) + 260
8   DVTFoundation                 	       0x1062c4128 DVTAssertInvalidatableObjectIsValid(_:) + 1488
9   IDESwiftPackageCore           	       0x12207d118 specialized IDESwiftPackageBuildable.blueprint.getter + 360
10  IDESwiftPackageCore           	       0x12206c44c @objc IDESwiftPackageBuildable.blueprint.getter + 28
11  XCBuildSupportCore            	       0x167371060 specialized Collection.map<A>(_:) + 184
12  XCBuildSupportCore            	       0x167367908 IDEXCBuildServiceSession.computeDependencyClosure(for:workspace:buildParameters:includeImplicitDependencies:) + 1008
13  XCBuildSupportCore            	       0x1673845cd IDEXCBuildSystemWorkspaceService.computeDependencyClosure(for:buildParameters:includeImplicitDependencies:) + 1
14  XCBuildSupportCore            	       0x1673847cd @objc closure #1 in IDEXCBuildSystemWorkspaceService.computeDependencyClosure(for:buildParameters:includeImplicitDependencies:) + 1
15  XCBuildSupportCore            	       0x16738c275 partial apply for @objc closure #1 in IDEXCBuildSystemWorkspaceService.computeDependencyClosure(for:buildParameters:includeImplicitDependencies:) + 1
16  XCBuildSupportCore            	       0x16738c251 thunk for @escaping @callee_guaranteed @Sendable @async () -> () + 1
17  XCBuildSupportCore            	       0x16738c259 partial apply for thunk for @escaping @callee_guaranteed @Sendable @async () -> () + 1
18  XCBuildSupportCore            	       0x167388475 specialized thunk for @escaping @callee_guaranteed @Sendable @async () -> (@out A) + 1
19  XCBuildSupportCore            	       0x16738c301 partial apply for specialized thunk for @escaping @callee_guaranteed @Sendable @async () -> (@out A) + 1
20  libswift_Concurrency.dylib    	       0x225aaa215 completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*) + 1
