### PR TITLE
Don't replay changes to invalidated child stores.

### LINKED ISSUE #2632: Crash in 1.5.2 - Unwrapping in IfLetStore, line 88
### Description

Noticed a crash when upgrading from 1.5.1 to 1.5.2

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

_No response_

### Actual behavior

_No response_

### Steps to reproduce

```
import ComposableArchitecture
import SwiftUI

struct ContentView: View {
    var body: some View {
        FeatureView(
            store: Store(
                initialState: Feature.State(),
                reducer: Feature.init
            )
        )
    }
}

#Preview {
    ContentView()
}

public struct FeatureView: View {
    let store: StoreOf<Feature>
    
    public var body: some View {
        ZStack {
            Button(action: { store.send(.tappedShowOverlay) }) {
                Text("Show overlay")
            }
            IfLetStore(
                store.scope(state: \.$destination.overlay, action: \.destination.overlay),
                then: OverlayView.init(store:)
            )
        }
    }
}

@Reducer
public struct Feature {
    public struct State {
        @PresentationState var destination: Destination.State?
    }
    
    public enum Action {
        case tappedShowOverlay
        
        case destination(PresentationAction<Destination.Action>)
    }
    
    public var body: some ReducerOf<Self> {
        Reduce {
            state, action in
            
            switch action {
            case .destination(.presented(.overlay(.delegate(let action)))):
                switch action {
                case .dismiss:
                    state.destination = nil
                    return .none
                }
                
            case .tappedShowOverlay:
                state.destination = .overlay(Overlay.State())
                return .none
                
            case .destination:
                return .none
            }
        }
        ._printChanges()
        .ifLet(\.$destination, action: \.destination) {
            Destination()
        }
    }
    
    @Reducer
    public struct Destination {
        public enum State {
            case overlay(Overlay.State)
        }
        
        public enum Action {
            case overlay(Overlay.Action)
        }
        
        public var body: some ReducerOf<Self> {
            Scope(state: \.overlay, action: \.overlay) {
                Overlay()
            }
        }
    }
}

public struct OverlayView: View {
    let store: StoreOf<Overlay>
    
    public var body: some View {
        Color.blue
            .overlay(content: { Text("Tap me") })
            .onTapGesture {
                store.send(.tapped)
            }
    }
}

@Reducer
public struct Overlay {
    public struct State {
        
    }
    
    public enum Action {
        case tapped
        
        case delegate(Delegate)
        
        public enum Delegate {
            case dismiss
        }
    }
    
    public var body: some ReducerOf<Self> {
        Reduce {
            state, action in
            
            switch action {
            case .tapped:
                return Effect.send(.delegate(.dismiss))
                
            case .delegate:
                return .none
            }
        }
    }
}

```

### The Composable Architecture version information

1.5.2

### Destination operating system

iOS17

### Xcode version information

Version 15.1 (15C65)

### Swift Compiler version information

```shell
swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
```

### PR DESCRIPTION
**Pull request by mbrandonw**
Fixes #2632.

I was able to get a unit test and integration test to verify the fix.

### CODE REVIEW

File: Sources/ComposableArchitecture/Store.swift [hunk 1]
```diff
@@ -463,7 +463,7 @@ public final class Store<State, Action> {
     )
   }
 
-  func scope<ChildState, ChildAction>(
+  @_spi(Internals) public func scope<ChildState, ChildAction>(
```
Comment (mbrandonw) [inline Sources/ComposableArchitecture/Store.swift:466]: Made some things SPI so that I could test without a `@testable` import.

**Comment by stephencelis** [comment]
Turns out we already had this fix on the observation beta for similar reasons. There were a few small differences so I updated it to more closely match observation. Will merge and release when it's green!
