### PR TITLE
Avoid simultaneous access crash on double-cancel

### LINKED ISSUE #136: SwiftUICaseStudies app crashes
**Describe the bug**
The culprit is the `cleanup` function in Effects > Cancellation

**To Reproduce**
1. Navigate to Elm-like Subscriptions
2. Turn on the clock
3. Navigate back to the root view

**Screenshot**
Screenshot 2020-05-26 at 23 18 48

**Environment**
 - Xcode 11.5
 - Swift 5.1
 - iOS 13.5

### PR DESCRIPTION
**Pull request by stephencelis**
Fixes #136.

### CODE REVIEW

File: Tests/ComposableArchitectureTests/EffectCancellationTests.swift [hunk 1]
```diff
@@ -223,17 +223,40 @@ final class EffectCancellationTests: XCTestCase {
 
     let expectation = self.expectation(description: "wait")
     effect
-      .sink(receiveCompletion: { _ in expectation.fulfill() }, receiveValue: { _ in })
+      .sink(receiveCompletion: { _ in
+        print("completed")
```
Comment (mbrandonw) [inline Tests/ComposableArchitectureTests/EffectCancellationTests.swift:227]: some clean up to do here...

File: Sources/ComposableArchitecture/Effects/Cancellation.swift [hunk 2]
```diff
@@ -76,12 +61,13 @@ extension Effect {
...
         cancellationCancellables[id] = nil
       }
     }
   }
 }
 
-var cancellationCancellables: [AnyHashable: [UUID: AnyCancellable]] = [:]
+var cancellationCancellables: [AnyHashable: Set<AnyCancellable>] = [:]
 let cancellablesLock = NSRecursiveLock()
+var isCancelling: Set<AnyHashable> = []
```
Comment (mbrandonw) [inline Sources/ComposableArchitecture/Effects/Cancellation.swift:73]: I think this goes away now right?

File: Tests/ComposableArchitectureTests/EffectCancellationTests.swift (hunk 1 above)
Comment (stephencelis) [reply Tests/ComposableArchitectureTests/EffectCancellationTests.swift:227]: oh ha yeah
