### PR TITLE
Fix Effect.throttle

### LINKED ISSUE #540: Incorrect throttling behavior
I know `Effect.throttle` is not yet public, and as per [this thread](https://forums.swift.org/t/type-inference-when-using-effect-throttle-operator/47994) I decided to "kick the tires". My first try was with some interesting behavior involving composable core location. I will try to make a complete example, but cannot guarantee it.

**To Reproduce**
Create a location manager through `ComposableCoreLocation` and `set` custom properties. Handle `didUpdateLocations` event from `LocationManager.Action` in your own reducer and return effect with a different event that, say, should push the coordinates to backend api every 15 seconds (the throttling part).

```swift
struct AppState {
    var latestLocations: [Location] = []
}

enum AppAction {
    case startUpdating
    case stopUpdating
    case locationManager(LocationManager.Action)
    case reportToApi
}

struct AppEnvironment {
    var managerId = "ManagerId"
    var locationManager: LocationManager = .live
    var scheduler: AnySchedulerOf<DispatchQueue>
    var reportId = "ReportId"
}

let appReducer = Reducer<AppState,AppAction,AppEnvironment> { state,action,env in

    switch action {
    case .stopUpdating:
        return .merge(
            env.locationManager.stopUpdatingLocation(id: env.managerId)
                .fireAndForget(),
            env.locationManager.destroy(id: env.managerId)
                .fireAndForget()
        )
    case .startUpdating:
        return .merge(
            env.locationManager.create(id: env.managerId)
                .map(AppAction.locationManager),
            env.locationManager.set(
                    id: env.managerId,
                    activityType: .other,
                    allowsBackgroundLocationUpdates: true,
                    desiredAccuracy: kCLLocationAccuracyNearestTenMeters
                    distanceFilter: 40
                )
                .fireAndForget(),
            env.locationManager.startUpdatingLocation(id: env.managerId)
                .fireAndForget()
        )
    case .locationManager(.didUpdateLocations(let locations)):
        state.latestLocations = locations
        // this is where the throttling happens
        return Effect(value: .reportLocation)
            .throttle(
                id: env.reportId,
                for: 15,
                scheduler: env.scheduler,
                latest: true
            )
    case .reportLocation:
        return .fireAndForget {
            print("[.reportLocation] \(Date().debugDescription)")
        }
    }
}
```

**Expected behavior**
I expected to see printed dates every 15 seconds.

**Screenshots**
Not screenshots, but actual console output:

```log
[.reportLocation] 2021-05-10 12:53:44 +0000
[.reportLocation] 2021-05-10 12:53:59 +0000
[.reportLocation] 2021-05-10 12:54:00 +0000
[.reportLocation] 2021-05-10 12:54:15 +0000
[.reportLocation] 2021-05-10 12:54:30 +0000
[.reportLocation] 2021-05-10 12:54:45 +0000
[.reportLocation] 2021-05-10 12:54:45 +0000
[.reportLocation] 2021-05-10 12:55:00 +0000
[.reportLocation] 2021-05-10 12:55:01 +0000
[.reportLocation] 2021-05-10 12:55:16 +0000
[.reportLocation] 2021-05-10 12:55:16 +0000
[.reportLocation] 2021-05-10 12:55:31 +0000
[.reportLocation] 2021-05-10 12:55:32 +0000
[.reportLocation] 2021-05-10 12:55:47 +0000
[.reportLocation] 2021-05-10 12:55:47 +0000
```

**Environment**
 - Xcode 12.5
 - watchOS 7.4

**Additional context**
Business logic is to track user's location and report it every 15 seconds to the API. The `startUpdating` and `stopUpdating` can be hooked to simple button in UI. To achieve the above output I used "City Run" simulated location on watchOS simulator.

### PR DESCRIPTION
**Pull request by stephencelis**
Fixes #540. Thanks to @kerryknight for diving into the issue.

### CODE REVIEW

File: Tests/ComposableArchitectureTests/Internal/EffectThrottleTests.swift [hunk 1]
```diff
@@ -134,4 +134,40 @@ final class EffectThrottleTests: XCTestCase {
...
+    scheduler.advance(by: 0.5)
+
+    runThrottledEffect(value: 2)
+
+    scheduler.advance(by: 0.5)
+
+    runThrottledEffect(value: 3)
+
+    // A second value is emitted right away.
+    XCTAssertEqual(values, [1, 2])
```
Comment (stephencelis) [inline Tests/ComposableArchitectureTests/Internal/EffectThrottleTests.swift:171]: Before the changes above, this emitted `[1, 2, 3]`.

**Review by mbrandonw — APPROVED** [review]
