### PR TITLE
Assorted fixes for collections of state

### LINKED ISSUE #21: Double Nested ForEachStore removal Bug
I have bug that I'm not sure if it's my implementation or CA. In the original app I found it I have a list of textfields that can have a carousel of images attached to them, as the user adds images they are added to the carousel. But they can also be removed, when removing the last item from the carousel it seems like there is an action that is still in the system looking for a now missing object in a `ForEachStore` Below is a minimum reproduction repo. 

https://github.com/ryantstone/LoopTest

### PR DESCRIPTION
**Pull request by stephencelis**
Fixes #21 and a few other things, which I will review.

### CODE REVIEW

File: Sources/ComposableArchitecture/Reducer.swift [hunk 1]
```diff
@@ -194,6 +194,17 @@ public struct Reducer<State, Action, Environment> {
...
+      assert(
+        index < globalState[keyPath: toLocalState].endIndex,
+        """
+        Index out of range. This can happen when a reducer that can remove the last element from \
+        an array is then combined with a "forEach" from that array. To avoid this and other \
+        index-related gotchas, consider using an "IdentifiedArray" of state instead. Or, combine \
+        your reducers so that the "forEach" comes before any reducer that can remove elements from \
+        its array.
+        """
+      )
```
Comment (stephencelis) [inline Sources/ComposableArchitecture/Reducer.swift:207]: This error message should #21. We can finesse the wording if any of it could be improved.

File: Sources/ComposableArchitecture/Reducer.swift [hunk 2]
```diff
@@ -238,7 +249,7 @@ public struct Reducer<State, Action, Environment> {
       guard let (id, localAction) = toLocalAction.extract(from: globalAction) else { return .none }
       return self.optional
         .reducer(
-          &globalState[keyPath: toLocalState][id],
+          &globalState[keyPath: toLocalState][id: id],
```
Comment (stephencelis) [inline Sources/ComposableArchitecture/Reducer.swift:252]: I've updated the interface to take an explicit `id` parameter to avoid any ambiguity for `Int`-based ids.

File: Sources/ComposableArchitecture/SwiftUI/IdentifiedArray.swift [hunk 3]
```diff
@@ -92,12 +92,15 @@ where ID: Hashable {
...
+  public subscript(id id: ID) -> Element? {
     get {
       self.dictionary[id]
     }
     _modify {
       yield &self.dictionary[id]
+      if self.dictionary[id] == nil {
+        self.ids.removeAll(where: { $0 == id })
+      }
     }
```
Comment (stephencelis) [inline Sources/ComposableArchitecture/SwiftUI/IdentifiedArray.swift:104]: We weren't properly cleaning up the `ids` array when `nil`-ing out elements.

File: Sources/ComposableArchitecture/SwiftUI/IdentifiedArray.swift [hunk 4]
```diff
@@ -115,6 +118,7 @@ where ID: Hashable {
...
   }
 
+  @discardableResult
```
Comment (stephencelis) [inline Sources/ComposableArchitecture/SwiftUI/IdentifiedArray.swift:121]: Stumbled upon this warning when writing tests.

File: Sources/ComposableArchitecture/SwiftUI/IdentifiedArray.swift [hunk 5]
```diff
@@ -138,7 +142,7 @@ where ID: Hashable {
   }
 
   public mutating func remove(atOffsets offsets: IndexSet) {
-    for offset in offsets {
+    for offset in offsets.reversed() {
```
Comment (stephencelis) [inline Sources/ComposableArchitecture/SwiftUI/IdentifiedArray.swift:145]: Tests caught a bug here, as well!
