### PR TITLE
Fix docs

### LINKED ISSUE #974: Gremlins in documentation
Just noticed this little gremlin hiding in the documentation for `.catchToEffect(_:)`. I'm assuming it's not intentional :)

https://github.com/pointfreeco/swift-composable-architecture/blob/5a62003f2892df2ab74290f07d060634f8f31da8/Sources/ComposableArchitecture/Effect.swift#L342

### PR DESCRIPTION
**Pull request by stephencelis**
Fixes #974.

### CODE REVIEW

File: Sources/ComposableArchitecture/Effect.swift [hunk 1]
```diff
@@ -339,7 +339,7 @@ extension Publisher {
   /// into a result and then applying passed in function to it.
   ///
   /// This is a convenience operator for writing ``Effect/catchToEffect()`` followed by a
-  /// ``Effect/map(_:)-28ghh``.
```
Comment (stephencelis) [inline Sources/ComposableArchitecture/Effect.swift:342]: This was still the identifier in Xcode 13.2, so I guess some DocC bugs have been fixed!

**Review by mbrandonw — APPROVED** [review]
