### PR TITLE
OpenURL fix for macCatalyst

### LINKED ISSUE #1428: OpenURL on protocol branch has issues with catalyst
### Description

The new additions to openURL for the protocol branch don’t build on Mac Catalyst. 

`'shared' is unavailable in Mac Catalyst`
`'NSWorkspace' is unavailable in Mac Catalyst `
`'open(_:configuration:completionHandler:)' is unavailable in Mac Catalyst `

### Checklist

- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues).

### Expected behavior

_No response_

### Actual behavior

_No response_

### Steps to reproduce

_No response_

### The Composable Architecture version information

protocol

### Destination operating system

Mac Catalyst

### Xcode version information

_No response_

### Swift Compiler version information

_No response_

### PR DESCRIPTION
**Pull request by stephencelis**
Fixes #1428.

Also gets CI running on `macCatalyst`.

### CODE REVIEW

File: Sources/Dependencies/Dependencies/OpenURL.swift [hunk 1]
```diff
@@ -22,7 +22,7 @@ private enum OpenURLKey: DependencyKey {
   static let liveValue = OpenURLEffect { url in
     let stream = AsyncStream<Bool> { continuation in
       let task = Task { @MainActor in
-        #if canImport(AppKit)
+        #if canImport(AppKit) && !targetEnvironment(macCatalyst)
```
Comment (tgrapperon) [inline Sources/Dependencies/Dependencies/OpenURL.swift:25]: Alternatively, we can be more explicit about the intent when selecting platforms and simplify the logic by removing negations using `os`:
```swift
#if os(iOS) && targetEnvironment(macCatalyst)

#elseif os(iOS)

#elseif os(tvOS)

#elseif os(watchOS)

#elseif os(macOS)

#else 

#endif
```

Comment (stephencelis) [reply Sources/Dependencies/Dependencies/OpenURL.swift:25]: Might revisit this in the future, as it is admittedly a bit confusing, but for now just focused on fixing the build 😅

**Review by mbrandonw — APPROVED** [review]
