### PR TITLE
Fix macOS <11 builds with Xcode 13 RC

### LINKED ISSUE #796: Fails to build for mac on XCode13 RC (no MacOS 12 sdk support yet)
**Describe the bug**
fails to build for MacOS with XCode13 RC

**To Reproduce**
open the project with XCode13 RC, build for mac.

**Expected behavior**
framework should build successfully

**Screenshots**
Screen Shot 2021-09-14 at 4 21 01 PM

**Environment**
  - swift-composable-architecture main branch
  - Xcode 13 RC (13A233)
  - Swift 5.5
  - OS: Big Sur 11.6

**Additional context**
XCode13 RC does not ship with MacOS12 SDK yet.

### PR DESCRIPTION
**Pull request by stephencelis**
Fixes #796.

### CODE REVIEW

**Review by mbrandonw — APPROVED** [review]

File: Tests/ComposableArchitectureTests/ViewStoreTests.swift [hunk 1]
```diff
@@ -137,7 +137,7 @@ final class ViewStoreTests: XCTestCase {
     XCTAssertNoDifference(results, [0, 1])
   }
 
-  #if compiler(>=5.5)
+  #if canImport(_Concurrency)
```
Comment (mbrandonw) [inline Tests/ComposableArchitectureTests/ViewStoreTests.swift:140]: should this be kept too?

```suggestion
  #if compiler(>=5.5) && canImport(_Concurrency)
```

**Review by mbrandonw — APPROVED** [review]
